language: java
sudo: required

services:
  - postgresql

install: true
notifications:
  email: false

before_install:
  - chmod +x mvnw


os: linux
dist: bionic
jdk: openjdk11
script:
  - ./mvnw test --no-transfer-progress

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: release