language: java

services:
  - postgresql

install: true
notifications:
  email: false

before_install:
  - chmod +x mvnw
  - COMMITS_SINCE_MAIN=$(git rev-list --count HEAD)
  - TAG_NAME="${TRAVIS_BRANCH}-m.${COMMITS_SINCE_MAIN}"
  - VERSION_NAME="0.0.1-${TAG_NAME}"
  - echo "Version ${VERSION_NAME}"
  - ./mvnw versions:set -DnewVersion="${VERSION_NAME}"

os: linux
dist: bionic
jdk: openjdk11
script:
  - ./mvnw test
  - ./mvnw compile jib:build -Dversion="${VERSION_NAME}"

deploy:
  provider: script
  script:
    curl https://cli-assets.heroku.com/install.sh | sh;  #install heroku
    docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com;  #login to registry.heroku.com
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
    git tag -a v0.0.1 -m "Release v0.0.1"
    git push
  on:
    branch: herokudeploy