version: '3.1'

services:

  jobPortalDb:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: p0stgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret

    ports:
      - 80:80
