CREATE TABLE EVENTS
(
    ID   INT PRIMARY KEY,
    DATE date,
    NAME text
);

CREATE TABLE CATEGORIES
(
    ID   INT PRIMARY KEY,
    NAME text,
    CONSTRAINT UC_CATEGORY_NAME
        UNIQUE (NAME)
);

CREATE TABLE COMPANY
(
    ID    INT PRIMARY KEY,
    ADMIN_ID INT NOT NULL,
    NAME  text
);

CREATE TABLE USERS
(
    ID         INT PRIMARY KEY,
    FIRST_NAME text,
    LAST_NAME  text,
    ROLE       text,
    COMPANY    INT,
    EMAIL      text,
    PASSWORD   text,
    CONSTRAINT fk_USERS_COMPANY
        FOREIGN KEY (COMPANY)
            REFERENCES COMPANY (ID),
    CONSTRAINT UC_USER_EMAIL
        UNIQUE (EMAIL)
);

-- Needs to be added after the tables were created -> circular dependency
ALTER TABLE COMPANY
ADD CONSTRAINT fk_ADMIN_COMPANY
    FOREIGN KEY (ADMIN_ID)
            REFERENCES USERS (ID);

CREATE TABLE REQUEST
(
    ID         INT PRIMARY KEY,
    REQUEST_BY  INT,
    APPROVED_BY INT,
    APPROVED_ON date,
    CONSTRAINT fk_REQUESTBY_USER
        FOREIGN KEY (REQUEST_BY)
            REFERENCES USERS (ID),
    CONSTRAINT fk_APPROVEDBY_USER
        FOREIGN KEY (APPROVED_BY)
            REFERENCES USERS (ID),
    CONSTRAINT UC_REQUEST_APPROVED
        UNIQUE (REQUEST_BY, APPROVED_BY)
);

CREATE TABLE POSTING
(
    ID            INT PRIMARY KEY,
    POSTED_BY      INT,
    POSTED_AT      date,
    DEADLINE      date,
    NUMBER_OF_VIEWS INT,
    NAME          text,
    DESCRIPTION   text,
    CATEGORY_ID    INT,
    REQUIREMENTS  text,
    CONSTRAINT fk_POSTEDBY_USER
        FOREIGN KEY (POSTED_BY)
            REFERENCES USERS (ID),
    CONSTRAINT fk_CATEGORYID_CATEGORIES
        FOREIGN KEY (CATEGORY_ID)
            REFERENCES CATEGORIES (ID)
);

CREATE TABLE APPLICATIONS
(
    ID INT PRIMARY KEY,
    POSTING_ID INT ,
    USER_ID INT ,
    DATE_APPLIED date ,
    EXPERIENCE INT ,
    WORK_EXPERIENCE text,
    EDUCATION text,
    CONSTRAINT fk_APPLICATIONS_POSTING
        FOREIGN KEY (POSTING_ID)
            REFERENCES POSTING (ID),
    CONSTRAINT fk_APPLICATIONS_USER
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID)
);

ALTER TABLE USERS ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE EVENTS ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE CATEGORIES ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE COMPANY ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE REQUEST ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE POSTING ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE APPLICATIONS ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;
