ALTER TABLE USERS
ALTER COLUMN ID SET NOT NULL;

ALTER TABLE EVENTS
ALTER COLUMN ID SET NOT NULL;

ALTER TABLE CATEGORIES
ALTER COLUMN ID SET NOT NULL;

ALTER TABLE COMPANY
ALTER COLUMN ID SET NOT NULL;

ALTER TABLE REQUEST
ALTER COLUMN ID SET NOT NULL;

ALTER TABLE POSTING
ALTER COLUMN ID SET NOT NULL;

ALTER TABLE APPLICATIONS
ALTER COLUMN ID SET NOT NULL;
