ALTER TABLE USERS
    ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE EVENTS
    ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE CATEGORIES
    ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE COMPANY
    ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE REQUEST
    ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE POSTING
    ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE APPLICATIONS
    ALTER COLUMN ID ADD GENERATED ALWAYS AS IDENTITY;